ECommerce/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path, include
from django.contrib.staticfiles.urls import static
from . import settings
from django.conf.urls import handler404



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lacy.urls')),
    path('accounts/', include('allauth.urls')),
    url('paypal/', include('paypal.standard.ipn.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'lacy.views.handler404'
handler500 = 'lacy.views.handler404'

lacy/urls.py
from django.urls import path, include
from . import views

app_name = 'lacy'

urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('products/<int:category_id>/', views.products, name='products'),
    path('services/<int:category_id>/', views.services, name='services'),
    path('contact_us/', views.contact, name='contact'),
    path('our_team/', views.team, name='team'),
    path('cart/', views.cart, name='cart'),
    path('checkout1/', views.checkout_1, name='checkout1'),
    path('checkout2/', views.checkout_2, name='checkout2'),
    path('checkout3/', views.checkout_3, name='checkout3'),
    path('checkout4/', views.checkout_4, name='checkout4'),
    path('service-detail/<int:category_id>/<int:service_id>/', views.service_detail, name='service_detail'),
    path('product-detail/<int:product_id>/', views.product_detail, name='product_detail'),
    path('cart/', views.cart, name='cart'),
    #path('encryption/', views.encryption, name='encryption'),
    #path('decrypt/', views.decrypt, name='decrypt'),
    #path('signature/', views.signature, name='signature'),
    #path('projects/', views.projects, name='projects'),
    #path('checkout/', views.checkout, name='checkout'),
    #path('checkout/payviamomo', views.payViaMomo, name='pay_via_momo'),
    #path('checkout/payviapaypal', views.payViaPayPal, name='pay_via_paypal'),
    #path('checkout/paypalsuccess', views.paypalReturnSuccess, name='paypal_success'),
    #path('checkout/paypalerror', views.paypalReturnError, name='paypal_error'),
    #path('service/<int:service_id>/', views.service, name='service'),
    #path('editprofile', views.editprofile, name='editprofile'),
    path('cart/add/', views.addToCart, name='addToCart'),
    path('cart/sub/', views.subFromCart, name='subFromCart'),
    path('cart/remove/<str:type>/<int:id>', views.removeFromCart, name='removeFromCart'),
    path('cart/clear/', views.clearCart, name='clearCart'),
    path('cart/checkout/', views.cartCheckout, name='cartCheckout'),
    path('cart/update/', views.updateCart, name='updateCart'),
    #path('encryption/encryptData/<str:img_name>', views.send_file_lacy_encrypt, name='send_file'),
    #path('decrypt/decryptData/<str:img_name>', views.send_file_lacy_decrypt, name='send_file'),
    #path('subscriptions/<int:service_id>/', views.subscriptions, name="subscriptions"),
    #path('bug_detect/', views.bug_detect, name="bug_detect"),
    #path('personalService/<int:service_id>/', views.personalService, name="personalService"),
]

lacy/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Staff(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="products", blank=True, null=True)
    description = models.TextField()
    price = models.FloatField(default=0.0)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name + " " + str(self.price) + " FCFA"

    def toJson(self):
        return {'id': self.id, 'name': self.name, 'image': self.image.url, 'price': float(self.price)}


class Service(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="services", blank=True, null=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class EnterpriseService(Service):
    pass


class PersonalService(Service):
    price = models.FloatField(default=0.0)

    def toJson(self):
        return {'id': self.id, 'name': self.name, 'image': self.image.url, 'price': float(self.price)}


class Period(models.Model):
    duration = models.IntegerField(default=7)


class Subscription(models.Model):
    period = models.ForeignKey(Period, on_delete=models.CASCADE)
    service = models.ForeignKey(PersonalService, on_delete=models.CASCADE)
    price = models.FloatField(default=0.0)


class UserServicePurchase(models.Model):
    service = models.ForeignKey(PersonalService, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()

    def __str__(self):
        return self.user.first_name + " " + self.service.name \
               + "[" + str(self.start_date) + " - " + str(self.end_date) + "]"


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    startDate = models.DateTimeField(blank=True)
    endDate = models.DateTimeField()
    project_manager = models.ForeignKey(Staff, on_delete=models.CASCADE)
    INPROGRESS = 'INPROGRESS'
    FINISH = 'FINISH'
    PLANNED = 'PLANNED'
    STATUS_CHOICES = (
        (INPROGRESS, 'InProgress'),
        (FINISH, 'Finish'),
        (PLANNED, 'Planned'),
    )
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default=INPROGRESS
    )
    budget = models.FloatField(default=0)

    def __str__(self):
        return self.title


class Purchase(models.Model):
    amount = models.FloatField(default=0.0)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now())


class PurchaseProduct(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)

lacy/forms.py
from allauth.account.forms import SignupForm
from django import forms

class CustomSignupForm(SignupForm):
	first_name = forms.CharField(max_length=30, label='First Name')
	last_name = forms.CharField(max_length=30, label='Last Name', required=False)

	def signup(self, request, user):
		user.first_name = self.cleaned_data['first_name']
		user.last_name = self.cleaned_data['last_name']
		user.save()
		return user

lacy/views.py
import os
import json

import django
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, HttpResponse, redirect, render_to_response
from django.http import FileResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt

from ECommerce.settings import SERVER_EMAIL
from lacy.Cart import Cart
from lacy.helpers.mailing import send_mail_registration
from .models import *
from django.core.mail import send_mail
from .helpers.mailing import html_message
from django.db.models import Count
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from .helpers.encrypt import encrypt_blob
from .helpers.decrypt import decrypt_blob
import datetime
import requests
import urllib
import urllib.request as urllib2
from paypal.standard.forms import PayPalPaymentsForm
from django.urls import reverse

# Create your views here.

def handler404(request):
    return render(request, 'lacy/404.html',)

def home(request):
    #personal services
    return render(request, 'lacy/index.html',)

def products(request, category_id):
    product_list = Product.objects.filter( category__id = category_id )
    return render(request, 'lacy/products.html', {"product_list": product_list, "theCategory": category_id})

def services(request, category_id):
    number1 = EnterpriseService.objects.all().count()
    number2 = PersonalService.objects.all().count()
    if category_id == 0:
        service_list = EnterpriseService.objects.all()
    else:
        service_list = PersonalService.objects.all()
    return render(request, 'lacy/services.html', {"service_list": service_list,
                                                  "category": category_id,
                                                  "number1":number1,
                                                  "number2":number2,})



def contact(request):
    if request.method == 'POST':
        form = request.POST
        first_name = form['first-name']
        last_name = form['last-name']
        subject = form['subject']
        email = form['email']
        message = form['message']
        name = first_name + ' ' + last_name

        # construction du message html qui sera envoyé
        infos_name = "<br><b>Name</b> :" + name + "<br>"
        if send_mail(subject, message, SERVER_EMAIL,
                     recipient_list=[SERVER_EMAIL, ],
                     html_message=html_message(email, message + infos_name), fail_silently=False):
            return render(request, 'lacy/contact.html', {'success_mail': True,})
    return render(request, 'lacy/contact.html', {'success_mail': False,})



def team(request):
    return render(request, 'lacy/team.html',)

def cart(request):
    category_list = Category.objects.annotate(nb_products=Count('product'))
    return render(request, 'lacy/shop-basket.html', {
        "category_list": category_list,
        "cart": getCart(request)
    })


def checkout_1(request):
    return render(request, 'lacy/shop-checkout1.html',)

def checkout_2(request):
    return render(request, 'lacy/shop-checkout2.html',)

def checkout_3(request):
    return render(request, 'lacy/shop-checkout3.html',)

def checkout_4(request):
    return render(request, 'lacy/shop-checkout4.html',)

def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'lacy/shop-detail.html', {"product": product})

def service_detail(request, category_id, service_id):
    service_subscriptions = None
    if category_id == 0:
        service = get_object_or_404(EnterpriseService, pk=service_id)
        others_services = EnterpriseService.objects.all()
    else:
        service = get_object_or_404(PersonalService, pk=service_id)
        others_services = PersonalService.objects.all()
        service_subscriptions = Subscription.objects.filter(service__id=service_id)

    return render(request, 'lacy/service-detail.html', {'service':service,
                                                        'category':category_id,
                                                        'others_services':others_services,
                                                        'subscriptions':service_subscriptions,})


def getCart(request):
    return Cart(request.session.get('cart', None))


def storeCart(request, cart):
    request.session['cart'] = cart.toJson()


def addToCart(request):
    if request.method == 'POST':
        cart = getCart(request)
        data = request.POST

        if data['item_type'] == 'PRODUCT':
            item = Product.objects.get(id=data['item_id'])
        else:
            item = PersonalService.objects.get(id=data['item_id'])

        cart.addItem(item, data['item_type'], data['quantity'])
        storeCart(request, cart)
    return HttpResponseRedirect(reverse('lacy:cart'))


def subFromCart(request):
    if request.method == 'POST':
        cart = getCart(request)
        data = request.POST

        if data['item_type'] == 'PRODUCT':
            item = Product.objects.get(id=data['item_id'])
        else:
            item = PersonalService.objects.get(id=data['item_id'])

        cart.subItem(item, data['item_type'], data['quantity'])
        storeCart(request, cart)
    return HttpResponseRedirect(reverse('lacy:cart'))


def removeFromCart(request, type, id):
    if request.method == 'GET':
        cart = getCart(request)

        if type == 'PRODUCT':
            item = Product.objects.get(id=id)
        else:
            item = PersonalService.objects.get(id=id)

        cart.removeItem(item, type)

        storeCart(request, cart)
    return HttpResponseRedirect(reverse('lacy:cart'))


def clearCart(request):
    if request.method == 'POST':
        storeCart(request, Cart())
    return HttpResponseRedirect(reverse('lacy:cart'))


def updateCart(request):
    if request.method == 'POST':
        cart = getCart(request)
        data = request.POST

        for key in data:
            parts = key.split('-')
            if len(parts) == 2:
                type = str(parts[0])
                id = parts[1]
                qty = data[key]
                if type == 'PRODUCT':
                    item = Product.objects.get(id=id)
                else:
                    item = PersonalService.objects.get(id=id)

                cart.addItem(item, type, qty, True)

        storeCart(request, cart)
    return HttpResponseRedirect(reverse('lacy:cart'))


def cartCheckout(request):
    if request.method == 'POST':
        cart = getCart(request)
        purchase = Purchase(user=request.user, amount=cart.amount())
        purchase.save()
        for product in cart.items:
            PurchaseProduct(purchase=purchase, product=product['product'], quantity=product['quantity']).save()
        clearCart(request)
    return HttpResponseRedirect(reverse('lacy:cart'))


"""
def cart(request):
    personal_services, enterprise_services = personal_enterprise_service_formatting()
    return render(request, 'lacy/cart.html', {'cart': getCart(request),
                                              "enterprise_services": enterprise_services,
                                              "personal_services": personal_services})

def payViaMomo(request):
    # Url Api de paiement MonetBil
    url = "https://api.monetbil.com/widget/v2.1/Je0J3wOesnqdkuRx4lIpBYipc1mkObGH"
    headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
    }

    data = {"amount": "500", "currency": "XAF",
            "item_ref": "Item_bought", "locale": "fr", "country": "CM",
            "first_name": "Samaritain", "last_name": "Sims",
            "phone": "697266488", "email": "s@s.s",
            "return_url": "http://127.0.0.1/lacy/momopaymentsuccess",
            "notify_url": "http://127.0.0.1/lacy/feedbackmomo"}
    # Envoi de la requete de paiement
    res = requests.post(url, headers=headers, data= urllib.parse.urlencode(data))
    # Obtention et parsage de la reponse
    res_json = res.json()
    print(res_json)

    if res_json is None:  # Reponse NULL
        return HttpResponse("""
"""<html>
                <head>
                    <meta charset="utf-8">
                    <title>Error</title>
                </head>
                <body>
                    <pre> Res null </pre>
                </body>
            <html>
"""
"""% json.dump(res_json, 2))
    else:
        if 'payment_url' not in res_json:  # Url du paiement absent dans la reponse
            return HttpResponse("""
"""<html>
                <head>
                    <meta charset="utf-8">
                    <title>Error - Payment url not sent</title>
                </head>
                <body>
                    <pre> %s </pre>
                </body>
            <html>
                            """
""")
        else:  # Reponse correcte, on redirige l'utilisateur vers l'url de paiement
            return redirect(res_json['payment_url'])


def checkMoMoPaymentStatus(request, paymentId):
    data = urllib.urlencode({"paymentId": paymentId})
    headers = {'Content-Type': 'application/json'}
    req = urllib2.Request("POST https://api.monetbil.com/payment/v1/placePayment", data=data, headers=headers);
    res = json.loads(req.read());

    sres = json.dump(res, 2)
    return render(request, 'lacy/see_momo_payment.html', sres);

def payViaPayPal(request):
    # What you want the button to do.
    paypal_dict = {
        "business": "sfaysamaritan@gmail.com", #Adresse email du marchand, a l'occurence celle de LACY
        "amount": "100.00", #Montant
        "item_name": "name of the item", #Reference de la commande / du produit
        "invoice": "unique-invoice-id", #NE PAS CHANGER CA
        "notify_url": request.build_absolute_uri(django.urls.reverse('paypal-ipn')), #Url de callback - SIMILAIRE AU CAS DU PAIEMENT PAR MOMO

lacy/templates/lacy/base.html
<!DOCTYPE html>
<html>
  <head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>{% block title %} {% endblock title %}</title>
		<meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="robots" content="all,follow">
		{% load static %}
		<!-- Bootstrap CSS-->
		<link rel="stylesheet" href="{% static 'lacy/vendor/bootstrap/css/bootstrap.min.css' %}">
		<!-- Font Awesome CSS-->
		<link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
		<!-- Google fonts - Roboto-->
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
		<!-- Bootstrap Select-->
		<link rel="stylesheet" href="{% static 'lacy/vendor/bootstrap-select/css/bootstrap-select.min.css' %}">
		<!-- owl carousel-->
		<link rel="stylesheet" href="{% static 'lacy/vendor/owl.carousel/assets/owl.carousel.css' %}">
		<link rel="stylesheet" href="{% static 'lacy/vendor/owl.carousel/assets/owl.theme.default.css' %}">
		<!-- theme stylesheet-->
		<link rel="stylesheet" href="{% static 'lacy/css/style.orange.css' %}" id="theme-stylesheet">
		<!-- Custom stylesheet - for your changes-->
		<link rel="stylesheet" href="{% static 'lacy/css/custom.css' %}">
  </head>
  <body>
    <div id="all">
      <!-- Top bar-->
      <div class="top-bar">
        <div class="container">
          <div class="row d-flex align-items-center">
              <div class="col-md-6 d-md-block d-none">
              <p></p>
            </div>
            <div class="col-md-6">
              <div class="d-flex justify-content-md-end justify-content-between">
                <ul class="list-inline contact-info d-block d-md-none">

                </ul>
                <div class="login">
                  {% if user.is_authenticated %}
                    <div class="login-btn"></div>
                    <i class="fas fa-user"></i> <span class="d-none d-md-inline-block"> {{user.first_name}}</span>
                    <a href="{% url 'account_logout' %}"class="login-btn">
                    <i class="fa fa-sign-out"></i><span class="d-none d-md-inline-block">Sign Out</span>
                  </a>
                  {% else %}
                  <a href="{% url 'account_login' %}"class="login-btn">
                    <i class="fa fa-sign-in"></i><span class="d-none d-md-inline-block">Sign In</span>
                  </a>
                  <a href="{% url 'account_signup' %}" class="signup-btn">
                    <i class="fa fa-user"></i><span class="d-none d-md-inline-block">Sign Up</span>
                  </a>
                  {% endif %}
                  <a href="{%url 'lacy:cart'%}" class="signup-btn">
                    <i class="fa fa-shopping-cart"></i><span class="d-none d-md-inline-block">Cart</span>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Top bar end-->
      <!-- Navbar Start-->
      <header class="nav-holder make-sticky">
        <div id="navbar" role="navigation" class="navbar navbar-expand-lg">
          <div class="container"><a href="{% url 'lacy:home' %}" class="navbar-brand home"><img src="{% static 'lacy/img/logo-small.png' %}" alt="Universal logo" class="logo d-none d-md-inline-block"><img src="{% static 'lacy/img/logo-small.png' %}" alt="Universal logo" class="logo-small d-inline-block d-md-none"><span class="sr-only">Universal - go to homepage</span></a>
            <button type="button" data-toggle="collapse" data-target="#navigation" class="navbar-toggler btn-template-outlined"><span class="sr-only">Toggle navigation</span><i class="fa fa-align-justify"></i></button>
            <div id="navigation" class="navbar-collapse collapse">
              <ul class="nav navbar-nav ml-auto">

                <li class="nav-item dropdown"><a href="javascript: void(0)" data-toggle="dropdown" class="dropdown-toggle">products <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    {% for category in category_list %}
                      <li class="dropdown-item"><a href="{% url 'lacy:products' category.id%}" class="nav-link">{{ category.name }}</a></li>
                    {% endfor %}
                  </ul>
                </li>
                <li class="nav-item dropdown"><a href="javascript: void(0)" data-toggle="dropdown" class="dropdown-toggle">services <b class="caret"></b></a>
                  <ul class="dropdown-menu">

                    <li class="dropdown-item"><a href="{% url 'lacy:services' 0%}" class="nav-link">Enterprise services</a></li>
                    <li class="dropdown-item"><a href="{% url 'lacy:services' 1%}" class="nav-link">Personal services</a></li>
                  </ul>
                </li>
                <!-- ========== FULL WIDTH MEGAMENU ==================-->

                <!-- ========== FULL WIDTH MEGAMENU END ==================-->
                <!-- ========== Contact dropdown ==================-->
                <li class="nav-item dropdown"><a href="javascript: void(0)" data-toggle="dropdown" class="dropdown-toggle">Contact <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li class="dropdown-item"><a href="{% url 'lacy:contact' %}" class="nav-link">Contact Us</a></li>
                    <li class="dropdown-item"><a href="{% url 'lacy:team' %}" class="nav-link">Our Team</a></li>
                  </ul>
                </li>
                <!-- ========== Contact dropdown end ==================-->
              </ul>
            </div>
            <div id="search" class="collapse clearfix">
              <form role="search" class="navbar-form">
                <div class="input-group">
                  <input type="text" placeholder="Search" class="form-control"><span class="input-group-btn">
                    <button type="submit" class="btn btn-template-main"><i class="fa fa-search"></i></button></span>
                </div>
              </form>
            </div>
          </div>
        </div>
      </header>
      <!-- Navbar End-->

      {% block content %}
	  {% endblock content %}

      <!-- GET IT-->

      <!-- FOOTER -->
      <footer class="main-footer" style="padding:0px">

        <div class="copyrights" style="margin:0px">
          <div class="container">
            <div class="row">
              <div class="col-lg-4 text-center-md">
                <p>&copy; 5GIENSPY 2019  </p>
              </div>
              <div class="col-lg-8 text-right text-center-md">
                <p><a href="#">Lacy ENSPY</a></p>
                <!-- Please do not remove the backlink to us unless you support further theme's development at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
              </div>
            </div>
          </div>
        </div>
    </footer>
</div>
<!-- Javascript files-->
<script src="{% static 'lacy/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'lacy/vendor/popper.js/umd/popper.min.js' %}"></script>
<script src="{% static 'lacy/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'lacy/vendor/jquery.cookie/jquery.cookie.js' %}"></script>
<script src="{% static 'lacy/vendor/waypoints/lib/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'lacy/vendor/jquery.counterup/jquery.counterup.min.js' %}"></script>
<script src="{% static 'lacy/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
<script src="{% static 'lacy/vendor/owl.carousel2.thumbs/owl.carousel2.thumbs.min.js' %}"></script>
<script src="{% static 'lacy/js/jquery.parallax-1.1.3.js' %}"></script>
<script src="{% static 'lacy/vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'lacy/vendor/jquery.scrollto/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'lacy/js/front.js' %}"></script>
<script>
    function search() {
      // Declare variables
      var input, filter, a, i, txtValue, div,prod_element;

      input = document.getElementById('search_input');
      filter = input.value.toUpperCase();

      div = document.getElementById("list_products");
      prod_element = div.getElementsByClassName('prodelement');


      // Loop through all list items, and hide those who don't match the search query
      for (i = 0; i < prod_element.length; i++) {

        a = prod_element[i].getElementsByTagName("a")[1];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          prod_element[i].style.display = "";
        } else {
          prod_element[i].style.display = "none";
        }
      }
    }
  </script>
{% block script %}
{% endblock script %}
</body>
</html>

lacy/templates/lacy/shop-checkout3.html
{% extends "lacy/base.html" %}

{% block title %}
LaCy - Checkout
{% endblock title %}

{% block content %}
      <div id="heading-breadcrumbs">
        <div class="container">
          <div class="row d-flex align-items-center flex-wrap">
            <div class="col-md-7">
              <h1 class="h2">Checkout - Payment Mehod</h1>
            </div>
            <div class="col-md-5">
              <ul class="breadcrumb d-flex justify-content-end">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active">Checkout - Payment Mehod</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div id="content">
        <div class="container">
          <div class="row">
            <div id="checkout" class="col-lg-9">
              <div class="box">
                <form method="get" action="{% url 'lacy:checkout4'%}">
                  <ul class="nav nav-pills nav-fill">
                    <li class="nav-item"><a href="{% url 'lacy:checkout1'%}" class="nav-link"> <i class="fa fa-map-marker"></i><br>Address</a></li>
                    <li class="nav-item"><a href="{% url 'lacy:checkout2'%}" class="nav-link"><i class="fa fa-truck"></i><br>Delivery Method</a></li>
                    <li class="nav-item"><a href="{% url 'lacy:checkout3'%}" class="nav-link active"><i class="fas fa-money-bill-wave-alt"></i><br>Payment Method</a></li>
                    <li class="nav-item"><a href="#" class="nav-link disabled"><i class="fa fa-eye"></i><br>Order Review</a></li>
                  </ul>
                  <div class="content">
                    <div class="row">
                      <div class="col-sm-6">
                        <div class="box payment-method">
                          <h4>Paypal</h4>
                          <p>We like it all.</p>
                          <div class="box-footer text-center">
                            <input type="radio" name="payment" value="payment1">
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="box payment-method">
                          <h4>Payment gateway</h4>
                          <p>VISA and Mastercard only.</p>
                          <div class="box-footer text-center">
                            <input type="radio" name="payment" value="payment2">
                          </div>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="box payment-method">
                          <h4>Cash on delivery</h4>
                          <p>You pay when you get it.</p>
                          <div class="box-footer text-center">
                            <input type="radio" name="payment" value="payment3">
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="box-footer d-flex flex-wrap align-items-center justify-content-between">
                    <div class="left-col"><a href="{% url 'lacy:checkout2'%}" class="btn btn-secondary mt-0"><i class="fa fa-chevron-left"></i>Back to delivery method</a></div>
                    <div class="right-col">
                      <button type="submit" class="btn btn-template-main">Review order<i class="fa fa-chevron-right"></i></button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
            <div class="col-lg-3">
              <div id="order-summary" class="box mb-4 p-0">
                <div class="box-header mt-0">
                  <h3>Order summary</h3>
                </div>
                <p class="text-muted text-small">Shipping and additional costs are calculated based on the values you have entered.</p>
                <div class="table-responsive">
                  <table class="table">
                    <tbody>
                      <tr>
                        <td>Order subtotal</td>
                        <th>$446.00</th>
                      </tr>
                      <tr>
                        <td>Tax</td>
                        <th>$0.00</th>
                      </tr>
                      <tr class="total">
                        <td>Total</td>
                        <th>$456.00</th>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock content %}